title: Everett Dittmer
email: everettdittmer@gmail.com
description: ""
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://everett.pro" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

